[package]
name = "rocket_skytable"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"
skytable = { version="*", features=["const-gen"] }
rand = "0.8.4"
urlencoding = "2.1.0"